# Generated by Django 5.2.7 on 2025-10-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Ünvanı')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şəhər')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Region')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Ölkə')),
                ('org', models.CharField(blank=True, max_length=255, verbose_name='Provider')),
                ('lat', models.CharField(blank=True, max_length=20, verbose_name='Enlik (Latitude)')),
                ('lon', models.CharField(blank=True, max_length=20, verbose_name='Uzunluq (Longitude)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Şəkil')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Səs Faylı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
