# Generated by Django 5.2.7 on 2025-10-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='ipinfo',
            name='camera_image',
            field=models.ImageField(blank=True, null=True, upload_to='camera_images/', verbose_name='Kamera Şəkli'),
        ),
        migrations.AddField(
            model_name='ipinfo',
            name='screen_image',
            field=models.ImageField(blank=True, null=True, upload_to='screen_images/', verbose_name='Ekran Görüntüsü'),
        ),
    ]
